#
# BSD 3-Clause
# (c) 2019, thorsten.johannvorderbrueggen@t-online.de                        
#

.PHONY: all clean

all:
	go build go_routine_printf.go

run: all
	go run go_routine_printf.go

clean:
	rm -f *~
	rm -f .*~
	rm -f go_routine_printf

distclean: clean
